### ISSUE TITLE
Provide configuraton file

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen.cfde.generator#1]
Please update the configuration file for 
* Protein master list
* Glycan master list
* GlyConnect data file

The configuration file can be found in [data folder ](https://github.com/glygener/glygen.cfde.generator/blob/main/data/files.csv). The documentation is in the [wiki](../wiki/File-configuration).

**Comment by jeet-vora** [comment]
The file_url has been changed to the latest version 1.12.2. Hopefully Robel doesn't delete the version.
data_format value has been removed
