### ISSUE TITLE
Error in glycan masterlist (G12422YW)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen.cfde.generator#14]
The glycan masterlist contains the GlyTouCan ID (G12422YW). This ID is not present in GlyGen and is archived in GlyTouCan. The prep-submission script (April version) fails at that point. 

FATAL: Term 'G12422YW' has no name: aborting, please check integrity of 'compound' reference file(s).

**Comment by ReneRanzinger** [comment]
Same for G23211TW.

**Comment by ReneRanzinger** [comment]
G25309LP

**Comment by ReneRanzinger** [comment]
G28497SE

**Comment by ReneRanzinger** [comment]
G30770II

**Comment by ReneRanzinger** [comment]
G35365SB

**Comment by ReneRanzinger** [comment]
G35720GD ... I  will stop here. Each iteration takes about 10 minutes. To sum it up the masterlist file needs to be fixed.

**Comment by jeet-vora** [comment]
the 1.12.2 files do not contain the above entries.

**Comment by ReneRanzinger** [comment]
This problem still persists with new IDs: G00222MO , G00786XQ

**Comment by ReneRanzinger** [comment]
G00948WV

**Comment by ReneRanzinger** [comment]
HELP-173 (ticket in CFDE)
