### ISSUE TITLE
Update confirguration files (June '23)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen.cfde.generator#34]
Update the [configuration files](https://github.com/glygener/glygen.cfde.generator/tree/main/data) for the data submission in June '23:
* files.csv
* mapping folder

**Blocker for**
* #35 
* #36
* #37
* #38

**Comment by jeet-vora** [comment]
I have updated the configuration files.csv and the files in the mapping folder for June 2023 release
The files.csv also has the new interlex terms in the data_type field. Please run the tsv file generation and let me know for any issues.
