### ISSUE TITLE
Rerun TSV file generation with new ignore files

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen.cfde.generator#37]
Based on #36 we will make new ignore files and regenerate the TSV files.

**Dependencies**
* #34 
* #35 
* #36 
* #39 

**Blocker for**
* #38

**Comment by jeet-vora** [comment]
@ReneRanzinger 
The submission prep script was run. 7 proteins have to be filtered out. See the list [here](https://gwu0.sharepoint.com/:t:/r/sites/GlyGenTeam-GRP/Shared%20Documents/CFDE/Base/Data%20Submission/2023%20June%20Submission/error_june_2023.txt?csf=1&web=1&e=bkYD95)

<img width="656" alt="image" src="https://github.com/glygener/glygen.cfde.generator/assets/25825266/42150f4f-dadd-4f70-92b6-fb35b45a650c">
 
Please create new TSVs and share them with me

**Comment by ReneRanzinger** [comment]
@jeet-vora No glycan issues?

**Comment by ReneRanzinger** [comment]
@jeet-vora done. I put the file into sharepoint: 2023.06.06-tsv.zip

**Comment by jeet-vora** [comment]
@ReneRanzinger 
New error file - https://gwu0.sharepoint.com/:t:/r/sites/GlyGenTeam-GRP/Shared%20Documents/CFDE/Base/Data%20Submission/2023%20June%20Submission/error_june_2023_06_07.txt?csf=1&web=1&e=RKgH6t

This time I got glycans (strange) and few new proteins. The glycans are obsolete and are from array experiments. The proteins are unreviewed mouse proteins.

Please generate the new file.

**Comment by ReneRanzinger** [comment]
@jeet-vora Done. 2023.06.07-tsv.zip
