### ISSUE TITLE
GlyTouCan to PubChem mapping

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen.cfde.generator#4]
The GlyTouCan to PubChem mapping file is needed. Its a two column file with first column being the GlyTouCan ID and the second column the PubChem ID. If a glycan does not have a PubChem ID it should not be in this file. The location of the file is in folder **data/mapping/** and the filename is **glytoucan2pubchem.csv**

**Comment by jeet-vora** [comment]
glytoucan2pubchem.csv has been added. The field header for GlyTouCan ID is glytoucan_ac and for PubChem ID is pubchem_cid. The glycans that have gtc_ac to pubchem_cid mapping are only present. Let me know for changes

**Comment by ReneRanzinger** [comment]
According to the documentation 
* https://github.com/nih-cfde/published-documentation/wiki/TableInfo:-compound.tsv
* https://github.com/nih-cfde/published-documentation/wiki/TableInfo:-biosample_substance.tsv

They are talking about SID (substance ID). They also use a different notation e.g., SID:5381226.

I can fix the later but please confirm SID.

**Comment by ReneRanzinger** [comment]
From Helpdesk:

Questions 2 and 3:

You are correct that the “id” field should be the PubChem CID. This was a typo in our documentation and has been fixed. Also, the compound and substance tables will not need prefixes, they only need the identification number. To view examples of entries, you can use the synthetic data generator: https://github.com/nih-cfde/C2M2syndatagenerator
