### ISSUE TITLE
Bug: data:2042 not accepted as file format

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen.cfde.generator#6]
In the config file are files listed with file format as "data:2042". The [pre-submission script ](https://github.com/nih-cfde/published-documentation/wiki/submission-prep-script) does not accept this as valid input.

**Comment by jeet-vora** [comment]
[For protein masterlist ](https://data.glygen.org/GLY_000001) I have changed the data_type to data:3021 (UniProtKB accession) http://edamontology.org/data_3021
There is no data_type for glycan masterlist as the EDAM does not list GlyTouCan ac
I am not sure if I should just add data_type is data:3021 (UniProtKB accession) and not mention GlyTouCan id for glyconnect data as it contains both proteins and glycans and even Uberon.
As the field is optional we can keep it blank as well.

**Comment by ReneRanzinger** [comment]
Leave it empty. I will adjust the code to allow for empty data type.

**Comment by jeet-vora** [comment]
Rene to make new issue for data format
