### ISSUE TITLE
Verify first test batch

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen.cfde.generator#8]
The package [tsv.zip](https://github.com/glygener/glygen.cfde.generator/files/8365781/tsv.zip) contains a first batch of generated files. Its based on the configuration in GitHub but only reads the first 5 lines of each file to make it easier to verify. Please keep in mind that the pre submission python will fail due to incorrect file format definition.

Please verify that all information is extracted and placed correctly.

**Comment by jeet-vora** [comment]
Checked the new batch 2022_04_05
